export const ASSAM_SCHEMES = [
  {
    id: 'as-orunodoi',
    name_en: 'Orunodoi Scheme',
    name_hi: 'ओरुनोदोई योजना',
    name_as: 'অৰুণোদয় আঁচনি',
    description_en: '₹1250/month for women-led BPL families.',
    description_hi: 'महिला नेतृत्व वाले बीपीएल परिवारों के लिए ₹1250/माह।',
    description_as: 'মহিলা পৰিচালিত বিপিএল পৰিয়ালৰ বাবে ₹১২৫০/মাহ।',
    category: 'womens_welfare',
    issuing_department: 'Finance Dept, Assam',
    benefits_en: 'Monthly DBT for household necessities.',
    benefits_hi: 'घरेलू आवश्यकताओं के लिए मासिक डीबीटी।',
    benefits_as: 'ঘৰুৱা প্ৰয়োজনৰ বাবে মাহেকীয়া ডিবিটি।',
    official_link: 'https://orunodoi.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'as-mukhyamantri-mahila-udyamita',
    name_en: 'CM Mahila Udyamita Abhiyan',
    name_hi: 'मुख्यमंत्री महिला उद्यमिता अभियान',
    name_as: 'মুখ্যমন্ত্ৰী মহিলা উদ্যমিতা অভিযান',
    description_en: 'Loans for women entrepreneurs in Assam.',
    description_hi: 'असम में महिला उद्यमियों के लिए ऋण।',
    description_as: 'অসমৰ মহিলা উদ্যোগীসকলৰ বাবে ঋণ।',
    category: 'business',
    issuing_department: 'Panchayat and Rural Development, Assam',
    benefits_en: 'Financial support and micro-credit for women-led businesses.',
    benefits_hi: 'महिलाओं के नेतृत्व वाले व्यवसायों के लिए वित्तीय सहायता और माइक्रो-क्रेडिट।',
    benefits_as: 'মহিলা পৰিচালিত ব্যৱসায়ৰ বাবে আৰ্থিক সাহায্য।',
    official_link: 'https://assam.gov.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'as-pragyan-bharati',
    name_en: 'Pragyan Bharati Scholarship',
    name_hi: 'प्रज्ञान भारती छात्रवृत्ति',
    name_as: 'প্ৰজ্ঞান ভাৰতী জলপানি',
    description_en: 'Free higher education and textbooks for state students.',
    description_hi: 'राज्य के छात्रों के लिए मुफ्त उच्च शिक्षा और पाठ्यपुस्तकें।',
    description_as: 'ৰাজ্যৰ ছাত্ৰ-ছাত্ৰীৰ বাবে বিনামূলীয়া উচ্চ শিক্ষা আৰু পাঠ্যপুথি।',
    category: 'scholarship',
    issuing_department: 'Higher Education Dept, Assam',
    benefits_en: 'Admission fee waiver and textbook subsidies.',
    benefits_hi: 'प्रवेश शुल्क में छूट और पाठ्यपुस्तक सब्सिडी।',
    benefits_as: 'নামভৰ্তি মাচুল ৰেহাই আৰু পাঠ্যপুথিৰ ৰাজসাহায্য।',
    official_link: 'https://highereducation.assam.gov.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'as-aanganwadi',
    name_en: 'Assam Anganwadi Services',
    name_hi: 'असम आंगनवाड़ी सेवाएं',
    name_as: 'অসম অংগনৱাড়ী সেৱা',
    description_en: 'Nutrition & health for under-6 children and mothers.',
    description_hi: '6 वर्ष से कम उम्र के बच्चों और माताओं के लिए पोषण और स्वास्थ्य।',
    description_as: '৬ বছৰৰ অনুৰ্ধৰ শিশু আৰু মাতৃৰ বাবে পুষ্টি আৰু স্বাস্থ্য।',
    category: 'healthcare',
    issuing_department: 'Social Welfare Dept, Assam',
    benefits_en: 'Supplementary nutrition and early education.',
    benefits_hi: 'पूरक पोषण और प्रारंभिक शिक्षा।',
    benefits_as: 'পৰিপূৰক পুষ্টি আৰু প্ৰাৰম্ভিক শিক্ষা।',
    official_link: 'https://socialwelfare.assam.gov.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'as-mukhyamantri-krishi-unnayan',
    name_en: 'CM Krishi Unnayan Yojana',
    name_hi: 'मुख्यमंत्री कृषि उन्नयन योजना',
    name_as: 'মুখ্যমন্ত্ৰী কৃষি উন্নয়ন যୋଜনা',
    description_en: 'Farm input subsidy for farmers in Assam.',
    description_hi: 'असम में किसानों के लिए फार्म इनपुट सब्सिडी।',
    description_as: 'অসমৰ কৃষকৰ বাবে কৃষি সামগ্ৰীৰ ৰাজসাহায্য।',
    category: 'farmer_subsidy',
    issuing_department: 'Agriculture Dept, Assam',
    benefits_en: 'Subsidies on seeds, fertilizers, and farm machinery.',
    benefits_hi: 'बीज, उर्वरक और कृषि मशीनरी पर सब्सिडी।',
    benefits_as: 'বীজ, সাৰ আৰু কৃষি যন্ত্ৰাংশত ৰাজসাহায্য।',
    official_link: 'https://diragri.assam.gov.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'as-chief-minister-samagra-gramya',
    name_en: 'CM Samagra Gramya Unnayan',
    name_hi: 'मुख्यमंत्री समग्र ग्राम्य उन्नयन',
    name_as: 'মুখ্যমন্ত্ৰী সমগ্ৰ গ্ৰাম্য উন্নয়ন',
    description_en: 'Rural infrastructure and livelihood development.',
    description_hi: 'ग्रामीण बुनियादी ढांचा और आजीविका विकास।',
    description_as: 'গ্ৰাম্য আন্তঃগাঁথনি আৰু জীৱিকা উন্নয়ন।',
    category: 'infrastructure',
    issuing_department: 'Panchayat and Rural Development, Assam',
    benefits_en: 'Tractor distribution and village development funds.',
    benefits_hi: 'ट्रैक्टर वितरण और ग्राम विकास निधि।',
    benefits_as: 'ট্ৰেক্টৰ বিতৰণ আৰু গাওঁ উন্নয়ন পুঁজি।',
    official_link: 'https://cmmms.assam.gov.in/',
    deadline: null,
    state: 'Assam',
    last_verified_at: '2026-07-25',
    required_documents: []
  }
];

export const ASSAM_ELIGIBILITY_RULES = [
  {
    id: 'rule-as-orunodoi',
    scheme_id: 'as-orunodoi',
    field: 'gender',
    operator: 'equals',
    value: 'female',
    match_reason_en: 'Financial aid provided to the primary female caretaker of the family.',
    match_reason_hi: 'परिवार की प्राथमिक महिला देखभालकर्ता को वित्तीय सहायता प्रदान की जाती है।',
    match_reason_as: 'পৰিয়ালৰ প্ৰাথমিক মহিলা সদস্যলৈ আৰ্থিক সাহায্য প্ৰদান কৰা হয়।'
  }
];
