export const GUJARAT_SCHEMES = [
  {
    id: 'gj-ikhedut',
    name_en: 'i-Khedut Portal Subsidy Schemes',
    name_hi: 'आई-खेडुत पोर्टल सब्सिडी योजनाएं',
    name_gu: 'આઇ-ખેડૂત પોર્ટલ સબસિડી યોજનાઓ',
    description_en: 'Agricultural input subsidies for farmers in Gujarat.',
    description_hi: 'गुजरात में किसानों के लिए कृषि इनपुट सब्सिडी।',
    description_gu: 'ગુજરાતમાં ખેડૂતો માટે કૃષિ ઇનપુટ સબસિડી.',
    category: 'farmer_subsidy',
    issuing_department: 'Agriculture Dept, Gujarat',
    benefits_en: 'Subsidies on various agricultural inputs, machinery, and equipment.',
    benefits_hi: 'विभिन्न कृषि इनपुट, मशीनरी और उपकरणों पर सब्सिडी।',
    benefits_gu: 'વિવિધ કૃષિ ઇનપુટ્સ, મશીનરી અને સાધનો પર સબસિડી.',
    official_link: 'https://ikhedut.gujarat.gov.in/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: [
      {
        key: 'aadhaar_card',
        name_en: 'Aadhaar Card',
        name_hi: 'आधार कार्ड',
        name_gu: 'આધાર કાર્ડ',
        helper_text_en: 'Issued by UIDAI.',
        helper_text_hi: 'यूआईडीएआई द्वारा जारी।',
        helper_text_gu: 'UIDAI દ્વારા જારી.',
        issuing_authority: 'UIDAI'
      }
    ]
  },
  {
    id: 'gj-mukhyamantri-amrutum',
    name_en: 'Mukhyamantri Amrutum (MA) Yojana',
    name_hi: 'मुख्यमंत्री अमृतम (एमए) योजना',
    name_gu: 'મુખ્યમંત્રી અમૃતમ (MA) યોજના',
    description_en: 'Health insurance scheme providing ₹5 lakh coverage for BPL families in Gujarat.',
    description_hi: 'गुजरात में बीपीएल परिवारों के लिए ₹5 लाख का स्वास्थ्य बीमा योजना।',
    description_gu: 'ગુજરાતમાં BPL પરિવારો માટે ₹5 લાખ કવરેજ પ્રદાન કરતી આરોગ્ય વીમા યોજના.',
    category: 'healthcare',
    issuing_department: 'Health Dept, Gujarat',
    benefits_en: 'Cashless health insurance coverage up to ₹5 lakh.',
    benefits_hi: '₹5 लाख तक का कैशलेस स्वास्थ्य बीमा कवरेज।',
    benefits_gu: '₹5 લાખ સુધીનું કેશલેસ આરોગ્ય વીમા કવરેજ.',
    official_link: 'http://magujarat.com/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'gj-vidya-sahai',
    name_en: 'Vidya Sahai Scholarship',
    name_hi: 'विद्या सहाय छात्रवृत्ति',
    name_gu: 'વિદ્યા સહાય શિષ્યવૃત્તિ',
    description_en: 'Post-matric scholarship for SC/ST/OBC students in Gujarat.',
    description_hi: 'गुजरात में एससी/एसटी/ओबीसी छात्रों के लिए पोस्ट-मैट्रिक छात्रवृत्ति।',
    description_gu: 'ગુજરાતમાં SC/ST/OBC વિદ્યાર્થીઓ માટે પોસ્ટ-મેટ્રિક શિષ્યવૃત્તિ.',
    category: 'scholarship',
    issuing_department: 'Social Justice Dept, Gujarat',
    benefits_en: 'Financial assistance for post-secondary education.',
    benefits_hi: 'माध्यमिक स्तर के बाद की शिक्षा के लिए वित्तीय सहायता।',
    benefits_gu: 'માધ્યમિક શિક્ષણ માટે નાણાકીય સહાય.',
    official_link: 'https://sje.gujarat.gov.in/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'gj-saat-nischay',
    name_en: 'Saat Nischay Yojana',
    name_hi: 'सात निश्चय योजना',
    name_gu: 'સાત નિશ્ચય યોજના',
    description_en: 'Interest-free education loan scheme for youth self-reliance in Gujarat.',
    description_hi: 'गुजरात में युवा आत्मनिर्भरता के लिए ब्याज मुक्त शिक्षा ऋण योजना।',
    description_gu: 'ગુજરાતમાં યુવા આત્મનિર્ભરતા માટે વ્યાજમુક્ત શિક્ષણ લોન યોજના.',
    category: 'education',
    issuing_department: 'Education Dept, Gujarat',
    benefits_en: 'Interest-free education loans for higher studies.',
    benefits_hi: 'उच्च शिक्षा के लिए ब्याज मुक्त शिक्षा ऋण।',
    benefits_gu: 'ઉચ્ચ અભ્યાસ માટે વ્યાજમુક્ત શિક્ષણ લોન.',
    official_link: 'https://gujarat.gov.in/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'gj-namo-laxmi',
    name_en: 'Namo Lakshmi Yojana',
    name_hi: 'नमो लक्ष्मी योजना',
    name_gu: 'નમો લક્ષ્મી યોજના',
    description_en: 'Scholarship of ₹50,000 for girl students in classes 9 to 12 in Gujarat.',
    description_hi: 'गुजरात में कक्षा 9 से 12 तक की छात्राओं के लिए ₹50,000 की छात्रवृत्ति।',
    description_gu: 'ગુજરાતમાં ધોરણ 9 થી 12 ની વિદ્યાર્થીનીઓ માટે ₹50,000 ની શિષ્યવૃત્તિ.',
    category: 'womens_welfare',
    issuing_department: 'Education Dept, Gujarat',
    benefits_en: '₹50,000 scholarship distributed over 4 years for high school girls.',
    benefits_hi: 'हाई स्कूल की लड़कियों के लिए 4 वर्षों में ₹50,000 की छात्रवृत्ति।',
    benefits_gu: 'હાઈસ્કૂલની છોકરીઓ માટે 4 વર્ષમાં ₹50,000 ની શિષ્યવૃત્તિ.',
    official_link: 'https://gujarat.gov.in/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'gj-kisan-suryoday',
    name_en: 'Kisan Suryoday Yojana',
    name_hi: 'किसान सूर्योदय योजना',
    name_gu: 'કિસાન સૂર્યોદય યોજના',
    description_en: 'Provides 3-phase electricity during daytime for agricultural irrigation in Gujarat.',
    description_hi: 'गुजरात में कृषि सिंचाई के लिए दिन के समय 3-चरण बिजली प्रदान करता है।',
    description_gu: 'ગુજરાતમાં કૃષિ સિંચાઈ માટે દિવસ દરમિયાન 3-ફેઝ વીજળી પૂરી પાડે છે.',
    category: 'farmer_subsidy',
    issuing_department: 'Energy Dept, Gujarat',
    benefits_en: 'Daytime agricultural power supply for farmers.',
    benefits_hi: 'किसानों के लिए दिन में कृषि बिजली आपूर्ति।',
    benefits_gu: 'ખેડૂતો માટે દિવસ દરમિયાન કૃષિ વીજ પુરવઠો.',
    official_link: 'https://gujarat.gov.in/',
    deadline: null,
    state: 'Gujarat',
    last_verified_at: '2026-07-25',
    required_documents: []
  }
];

export const GUJARAT_ELIGIBILITY_RULES = [
  {
    id: 'rule-gj-ma-income',
    scheme_id: 'gj-mukhyamantri-amrutum',
    field: 'annual_income_band',
    operator: 'in',
    value: ['below_1L', '1L_2L'],
    match_reason_en: 'Eligible for MA Yojana based on BPL status.',
    match_reason_hi: 'बीपीएल स्थिति के आधार पर एमए योजना के लिए पात्र।',
    match_reason_gu: 'બીપીએલ દરજ્જાના આધારે એમએ યોજના માટે લાયક.'
  },
  {
    id: 'rule-gj-namo-gender',
    scheme_id: 'gj-namo-laxmi',
    field: 'gender',
    operator: 'equals',
    value: 'female',
    match_reason_en: 'Targeted scholarship for female students.',
    match_reason_hi: 'महिला छात्रों के लिए लक्षित छात्रवृत्ति।',
    match_reason_gu: 'વિદ્યાર્થીનીઓ માટે લક્ષિત શિષ્યવૃત્તિ.'
  }
];
