export const KERALA_SCHEMES = [
  {
    id: 'kl-kudumbashree',
    name_en: 'Kudumbashree (Poverty Eradication and Women Empowerment)',
    name_hi: 'कुटुंबश्री (गरीबी उन्मूलन और महिला सशक्तिकरण)',
    name_ml: 'കുടുംബശ്രീ (ദാരിദ്ര്യ നിർമ്മാർജ്ജനവും സ്ത്രീ ശാക്തീകരണവും)',
    description_en: 'Kerala government’s poverty eradication and women empowerment mission implemented through community-based organizations (SHGs) to promote micro-enterprises and sustainable livelihoods.',
    description_hi: 'केरल सरकार का गरीबी उन्मूलन और महिला सशक्तिकरण मिशन सामुदायिक संगठनों (SHGs) के माध्यम से सूक्ष्म उद्यमों और टिकाऊ आजीविका को बढ़ावा देने के लिए लागू किया गया है।',
    description_ml: 'സ്ത്രീകളുടെ കൂട്ടായ്മകളിലൂടെ (SHG) സൂക്ഷ്മ സംരംഭങ്ങളും സുസ്ഥിര ഉപജീവനമാർഗങ്ങളും പ്രോത്സാഹിപ്പിക്കുന്നതിനായി കേരള സർക്കാർ നടപ്പിലാക്കുന്ന ദാരിദ്ര്യ നിർമ്മാർജ്ജന, സ്ത്രീ ശാക്തീകരണ മിഷൻ.',
    category: 'womens_welfare',
    issuing_department: 'Local Self Government Department, Kerala',
    benefits_en: 'Access to micro-credit, entrepreneurship training, and livelihood support.',
    benefits_hi: 'सूक्ष्म ऋण, उद्यमिता प्रशिक्षण और आजीविका सहायता तक पहुंच।',
    benefits_ml: 'മൈക്രോ ക്രെഡിറ്റ്, സംരംഭകത്വ പരിശീലനം, ഉപജീവന സഹായം എന്നിവ ലഭ്യമാക്കുന്നു.',
    official_link: 'https://www.kudumbashree.org/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-scholarship-sc-st',
    name_en: 'Kerala SC/ST Pre & Post Matric Scholarship',
    name_hi: 'केरल एससी/एसटी प्री एवं पोस्ट मैट्रिक छात्रवृत्ति',
    name_ml: 'കേരള SC/ST പ്രീ & പോസ്റ്റ് മെട്രിക് സ്കോളർഷിപ്പ്',
    description_en: 'Financial assistance for students from SC and ST communities pursuing pre-matric and post-matric studies to cover tuition fees, maintenance, and other educational expenses.',
    description_hi: 'एससी और एसटी समुदायों के छात्रों को प्री-मैट्रिक और पोस्ट-मैट्रिक पढ़ाई के लिए ट्यूशन फीस, रखरखाव और अन्य शैक्षिक खर्चों को कवर करने के लिए वित्तीय सहायता।',
    description_ml: 'SC, ST വിഭാഗങ്ങളിലെ വിദ്യാർത്ഥികൾക്ക് പഠനച്ചെലവുകൾ, ട്യൂഷൻ ഫീസ് എന്നിവയ്ക്കായി നൽകുന്ന പ്രീ-മെട്രിക്, പോസ്റ്റ്-മെട്രിക് സ്കോളർഷിപ്പുകൾ.',
    category: 'scholarship',
    issuing_department: 'SC/ST Development Department, Kerala',
    benefits_en: 'Tuition fee reimbursement and monthly stipend.',
    benefits_hi: 'ट्यूशन फीस की प्रतिपूर्ति और मासिक वजीफा।',
    benefits_ml: 'ട്യൂഷൻ ഫീസ് റീഇംബേഴ്സ്മെന്റും പ്രതിമാസ സ്റ്റൈപ്പൻഡും.',
    official_link: 'https://egrantz.kerala.gov.in/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-karshaka-pension',
    name_en: 'Kerala Karshaka Pension Scheme',
    name_hi: 'केरल कृषक पेंशन योजना',
    name_ml: 'കേരള കർഷക പെൻഷൻ പദ്ധതി',
    description_en: 'Monthly pension scheme for small and marginal farmers aged 60 and above in Kerala to ensure their social security.',
    description_hi: 'केरल में 60 वर्ष और उससे अधिक आयु के छोटे और सीमांत किसानों की सामाजिक सुरक्षा सुनिश्चित करने के लिए मासिक पेंशन योजना।',
    description_ml: 'കേരളത്തിലെ 60 വയസ്സും അതിനുമുകളിലും പ്രായമുള്ള ചെറുകിട നാമമാത്ര കർഷകർക്ക് സാമൂഹ്യ സുരക്ഷ ഉറപ്പാക്കുന്ന പ്രതിമാസ പെൻഷൻ പദ്ധതി.',
    category: 'pension',
    issuing_department: 'Agriculture Development and Farmers Welfare Department, Kerala',
    benefits_en: '₹1,500 monthly pension transferred directly to the farmer’s bank account.',
    benefits_hi: 'किसान के बैंक खाते में सीधे ₹1,500 की मासिक पेंशन हस्तांतरित।',
    benefits_ml: 'കർഷകന്റെ ബാങ്ക് അക്കൗണ്ടിലേക്ക് നേരിട്ട് ₹1,500 പ്രതിമാസ പെൻഷൻ ലഭിക്കും.',
    official_link: 'https://sevana.kerala.gov.in/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-aashraya',
    name_en: 'Aashraya (Destitute Identification & Rehabilitation Project)',
    name_hi: 'आश्रय (निराश्रित पहचान और पुनर्वास परियोजना)',
    name_ml: 'ആശ്രയ (അഗതി പുനരധിവാസ പദ്ധതി)',
    description_en: 'A holistic welfare project by Kudumbashree offering housing, food, healthcare, and social security to the extreme poor and destitute families (BPL).',
    description_hi: 'कुटुंबश्री की एक समग्र कल्याणकारी परियोजना जो अत्यधिक गरीब और निराश्रित परिवारों (BPL) को आवास, भोजन, स्वास्थ्य सेवा और सामाजिक सुरक्षा प्रदान करती है।',
    description_ml: 'അങ്ങേയറ്റം ദരിദ്രരായ (BPL) അഗതി കുടുംബങ്ങൾക്ക് പാർപ്പിടം, ഭക്ഷണം, ആരോഗ്യ സംരക്ഷണം, സാമൂഹ്യ സുരക്ഷ എന്നിവ ലഭ്യമാക്കുന്ന കുടുംബശ്രീയുടെ സമഗ്ര ക്ഷേമ പദ്ധതി.',
    category: 'housing',
    issuing_department: 'Local Self Government Department, Kerala',
    benefits_en: 'Comprehensive support including shelter, pension, and medical care.',
    benefits_hi: 'आवास, पेंशन और चिकित्सा देखभाल सहित व्यापक सहायता।',
    benefits_ml: 'പാർപ്പിടം, പെൻഷൻ, വൈദ്യസഹായം എന്നിവ ഉൾപ്പെടെയുള്ള സമഗ്ര പിന്തുണ.',
    official_link: 'https://www.kudumbashree.org/pages/155',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-welfare-fund-fishermen',
    name_en: 'Matsyafed Fishermen Welfare Fund',
    name_hi: 'मत्स्यफेड मछुआरा कल्याण कोष',
    name_ml: 'മത്സ്യത്തൊഴിലാളി ക്ഷേമനിധി',
    description_en: 'Welfare schemes for registered traditional and coastal fishermen, providing financial aid for education, marriage, housing, and pension benefits.',
    description_hi: 'पंजीकृत पारंपरिक और तटीय मछुआरों के लिए कल्याणकारी योजनाएं, जो शिक्षा, विवाह, आवास और पेंशन लाभों के लिए वित्तीय सहायता प्रदान करती हैं।',
    description_ml: 'രജിസ്റ്റർ ചെയ്ത പരമ്പരാഗത തീരദേശ മത്സ്യത്തൊഴിലാളികൾക്ക് വിദ്യാഭ്യാസം, വിവാഹം, പാർപ്പിടം, പെൻഷൻ എന്നിവയ്ക്ക് സാമ്പത്തിക സഹായം നൽകുന്ന ക്ഷേമ പദ്ധതികൾ.',
    category: 'welfare',
    issuing_department: 'Fisheries Department, Kerala',
    benefits_en: 'Grants, pensions, and insurance for fishing communities.',
    benefits_hi: 'मछुआरा समुदायों के लिए अनुदान, पेंशन और बीमा।',
    benefits_ml: 'മത്സ്യത്തൊഴിലാളി സമൂഹങ്ങൾക്ക് ഗ്രാന്റുകൾ, പെൻഷൻ, ഇൻഷുറൻസ് എന്നിവ.',
    official_link: 'https://fisheries.kerala.gov.in/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-snehapoorvam',
    name_en: 'Snehapoorvam Scholarship Scheme',
    name_hi: 'स्नेहपूर्णम छात्रवृत्ति योजना',
    name_ml: 'സ്നേഹപൂർവ്വം സ്കോളർഷിപ്പ് പദ്ധതി',
    description_en: 'Provides financial assistance for the education of orphan children and children living with HIV to ensure they do not drop out of school.',
    description_hi: 'अनाथ बच्चों और एचआईवी से पीड़ित बच्चों की शिक्षा के लिए वित्तीय सहायता प्रदान करता है ताकि यह सुनिश्चित किया जा सके कि वे स्कूल न छोड़ें।',
    description_ml: 'അനാഥരായ കുട്ടികൾക്കും എച്ച്.ഐ.വി ബാധിതരായ കുട്ടികൾക്കും പഠനം തുടരുന്നതിനായി സാമ്പത്തിക സഹായം നൽകുന്ന പദ്ധതി.',
    category: 'scholarship',
    issuing_department: 'Kerala Social Security Mission (KSSM)',
    benefits_en: 'Monthly financial assistance ranging from ₹300 to ₹1,000 depending on the class of study.',
    benefits_hi: 'अध्ययन की कक्षा के आधार पर ₹300 से ₹1,000 तक की मासिक वित्तीय सहायता।',
    benefits_ml: 'പഠിക്കുന്ന ക്ലാസ്സിനനുസരിച്ച് മാസം ₹300 മുതൽ ₹1,000 വരെ സാമ്പത്തിക സഹായം.',
    official_link: 'http://socialsecuritymission.gov.in/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-nirmal-bhavan',
    name_en: 'Nirmal Bhavanam Housing Scheme',
    name_hi: 'निर्मल भवनम आवास योजना',
    name_ml: 'നിർമ്മൽ ഭവനം ഭവന പദ്ധതി',
    description_en: 'Aimed at providing safe and free housing for homeless families belonging to Scheduled Castes and Scheduled Tribes in Kerala.',
    description_hi: 'केरल में अनुसूचित जाति और अनुसूचित जनजाति के बेघर परिवारों को सुरक्षित और मुफ्त आवास प्रदान करने के उद्देश्य से।',
    description_ml: 'കേരളത്തിലെ പട്ടികജാതി-പട്ടികവർഗ്ഗ വിഭാഗത്തിൽപ്പെട്ട ഭവനരഹിതരായ കുടുംബങ്ങൾക്ക് സുരക്ഷിതവും സൗജന്യവുമായ വീടുകൾ നൽകുന്ന പദ്ധതി.',
    category: 'housing',
    issuing_department: 'SC/ST Development Department, Kerala',
    benefits_en: 'Financial assistance and resources to construct a new house.',
    benefits_hi: 'नया घर बनाने के लिए वित्तीय सहायता और संसाधन।',
    benefits_ml: 'പുതിയ വീട് നിർമ്മിക്കുന്നതിനുള്ള സാമ്പത്തിക സഹായം.',
    official_link: 'https://scdd.kerala.gov.in/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'kl-yuva-keralam',
    name_en: 'Yuva Keralam (Employment and Skill Training)',
    name_hi: 'युवा केरलम (रोजगार और कौशल प्रशिक्षण)',
    name_ml: 'യുവകേരളം (തൊഴിൽ, നൈപുണ്യ പരിശീലനം)',
    description_en: 'Provides free skill development training and placement assistance for unemployed rural and urban youth in Kerala.',
    description_hi: 'केरल में बेरोजगार ग्रामीण और शहरी युवाओं के लिए मुफ्त कौशल विकास प्रशिक्षण और प्लेसमेंट सहायता प्रदान करता है।',
    description_ml: 'കേരളത്തിലെ തൊഴിൽരഹിതരായ ഗ്രാമീണ-നഗര പ്രദേശങ്ങളിലെ യുവാക്കൾക്ക് സൗജന്യ നൈപുണ്യ വികസന പരിശീലനവും തൊഴിൽ സഹായവും നൽകുന്നു.',
    category: 'welfare',
    issuing_department: 'Kudumbashree / NULM Kerala',
    benefits_en: 'Free industry-relevant skill training and guaranteed placement opportunities.',
    benefits_hi: 'उद्योग-प्रासंगिक मुफ्त कौशल प्रशिक्षण और रोजगार के अवसर।',
    benefits_ml: 'സൗജന്യ നൈപുണ്യ പരിശീലനവും തൊഴിലവസരങ്ങളും ഉറപ്പാക്കുന്നു.',
    official_link: 'https://www.kudumbashree.org/',
    deadline: null,
    state: 'Kerala',
    last_verified_at: '2026-07-25',
    required_documents: []
  }
];

export const KERALA_ELIGIBILITY_RULES = [
  {
    id: 'rule-kl-karshaka-age',
    scheme_id: 'kl-karshaka-pension',
    field: 'age',
    operator: 'greater_than_or_equal',
    value: 60,
    match_reason_en: 'Farmers aged 60 and above are eligible for this pension.',
    match_reason_hi: '60 वर्ष और उससे अधिक आयु के किसान इस पेंशन के पात्र हैं।',
    match_reason_ml: '60 വയസ്സും അതിനുമുകളിലും പ്രായമുള്ള കർഷകർക്ക് ഈ പെൻഷന് അർഹതയുണ്ട്.'
  },
  {
    id: 'rule-kl-scholarship-scst',
    scheme_id: 'kl-scholarship-sc-st',
    field: 'social_category',
    operator: 'in',
    value: ['SC', 'ST'],
    match_reason_en: 'Students belonging to SC/ST communities are eligible for this scholarship.',
    match_reason_hi: 'एससी/एसटी समुदाय के छात्र इस छात्रवृत्ति के लिए पात्र हैं।',
    match_reason_ml: 'SC/ST വിഭാഗങ്ങളിൽപ്പെടുന്ന വിദ്യാർത്ഥികൾക്ക് ഈ സ്കോളർഷിപ്പിന് അർഹതയുണ്ട്.'
  },
  {
    id: 'rule-kl-aashraya-income',
    scheme_id: 'kl-aashraya',
    field: 'annual_income_band',
    operator: 'equals',
    value: 'below_1L',
    match_reason_en: 'Extreme poor and destitute BPL families are eligible.',
    match_reason_hi: 'अत्यधिक गरीब और निराश्रित बीपीएल परिवार पात्र हैं।',
    match_reason_ml: 'അങ്ങേയറ്റം ദരിദ്രരായ BPL കുടുംബങ്ങൾക്ക് അർഹതയുണ്ട്.'
  },
  {
    id: 'rule-kl-snehapoorvam-age',
    scheme_id: 'kl-snehapoorvam',
    field: 'age',
    operator: 'less_than_or_equal',
    value: 18,
    match_reason_en: 'Vulnerable children and orphans below 18 years are covered.',
    match_reason_hi: '18 वर्ष से कम उम्र के कमजोर बच्चे और अनाथ इसके अंतर्गत आते हैं।',
    match_reason_ml: '18 വയസ്സിന് താഴെയുള്ള അനാഥരായ കുട്ടികൾക്ക് അർഹതയുണ്ട്.'
  }
];

export const KERALA_RAG_DOCUMENTS = [
  {
    id: 'doc-kl-kudumbashree-clause-1',
    scheme_id: 'kl-kudumbashree',
    clause_label: 'Kudumbashree — SHG Formation & Micro-Credit Access Rules',
    content: 'Kudumbashree operates through three-tier community structures: Neighbourhood Groups (NHGs) of 10-20 women, Area Development Societies (ADS), and Community Development Societies (CDS). Women in BPL families as identified through Nine Point Risk Index are primary members. NHGs are eligible for revolving fund assistance and linkage to bank credit up to ₹5 lakh for micro-enterprises.',
    language: 'en',
    last_verified_at: '2026-07-25'
  },
  {
    id: 'doc-kl-scholarship-clause-1',
    scheme_id: 'kl-scholarship-sc-st',
    clause_label: 'Kerala eGrantz — SC/ST Scholarship Income Limit & Application Process',
    content: 'SC students with family income up to ₹6 lakh per annum and ST students without any income ceiling are eligible for post-matric scholarship in Kerala. Applications are submitted through the eGrantz portal. Fresh income certificate from Village Officer, community certificate, and institutional enrollment certificate are mandatory documents.',
    language: 'en',
    last_verified_at: '2026-07-25'
  },
  {
    id: 'doc-kl-pension-clause-1',
    scheme_id: 'kl-karshaka-pension',
    clause_label: 'Kerala Karshaka Pension — Eligibility Age, Land Holding & Income Criteria',
    content: 'Farmers aged 60 years and above with land holding not exceeding 2 hectares are eligible for Kerala Karshaka Pension of ₹1,500 per month. The applicant must be primarily dependent on agriculture for livelihood and should not be receiving any other government pension. Applications are processed through the Akshaya centres or Agriculture Department offices.',
    language: 'en',
    last_verified_at: '2026-07-25'
  }
];
