export const TAMILNADU_SCHEMES = [
  {
    id: 'tn-chief-minister-breakfast',
    name_en: 'Chief Minister Breakfast Scheme',
    name_hi: 'मुख्यमंत्री नाश्ता योजना',
    name_ta: 'முதலமைச்சர் காலை உணவுத் திட்டம்',
    description_en: 'Provides free nutritious breakfast to primary school students (Classes 1 to 5) studying in government schools across Tamil Nadu.',
    description_hi: 'तमिलनाडु भर के सरकारी स्कूलों में पढ़ने वाले प्राथमिक स्कूल के छात्रों (कक्षा 1 से 5) को मुफ्त पौष्टिक नाश्ता प्रदान करता है।',
    description_ta: 'தமிழ்நாடு முழுவதும் உள்ள அரசுப் பள்ளிகளில் படிக்கும் தொடக்கப் பள்ளி மாணவர்களுக்கு (1 முதல் 5 ஆம் வகுப்பு வரை) இலவச ஊட்டச்சத்து மிக்க காலை உணவை வழங்குகிறது.',
    category: 'education',
    issuing_department: 'Social Welfare and Nutritious Meal Programme Department, Tamil Nadu',
    benefits_en: 'Free hot nutritious breakfast on all school working days.',
    benefits_hi: 'सभी स्कूल कार्य दिवसों पर मुफ्त गर्म पौष्टिक नाश्ता।',
    benefits_ta: 'அனைத்து பள்ளி வேலை நாட்களிலும் இலவச சூடான சத்தான காலை உணவு.',
    official_link: 'https://cmmbs.tn.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-moovalur-ramamirtham-scholarship',
    name_en: 'Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn)',
    name_hi: 'मूवलूर रामामिरथम अम्मैयार उच्च शिक्षा योजना (पुधुमई पेन)',
    name_ta: 'மூவலூர் ராமாமிர்தம் அம்மையார் உயர்கல்வி உறுதித் திட்டம் (புதுமைப் பெண்)',
    description_en: 'Financial assistance of ₹1,000 per month for girls who studied Classes 6 to 12 in state government schools to pursue higher education.',
    description_hi: 'राज्य के सरकारी स्कूलों में कक्षा 6 से 12 तक पढ़ने वाली लड़कियों को उच्च शिक्षा प्राप्त करने के लिए ₹1,000 प्रति माह की वित्तीय सहायता।',
    description_ta: 'அரசுப் பள்ளிகளில் 6 முதல் 12 ஆம் வகுப்பு வரை படித்த மாணவிகள் உயர்கல்வி பயில மாதம் ₹1,000 நிதியுதவி.',
    category: 'scholarship',
    issuing_department: 'Social Welfare and Women Empowerment Department, Tamil Nadu',
    benefits_en: '₹1,000 credited directly to the student’s bank account every month until course completion.',
    benefits_hi: 'कोर्स पूरा होने तक हर महीने सीधे छात्र के बैंक खाते में ₹1,000 जमा किए जाते हैं।',
    benefits_ta: 'படிப்பு முடியும் வரை ஒவ்வொரு மாதமும் மாணவியின் வங்கிக் கணக்கில் நேரடியாக ₹1,000 வரவு வைக்கப்படும்.',
    official_link: 'https://pudhumaipenn.tn.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-kalaignar-magalir-urimai-thittam',
    name_en: 'Kalaignar Magalir Urimai Thittam',
    name_hi: 'कलैगनार मगलिर उरिमई थित्तम',
    name_ta: 'கலைஞர் மகளிர் உரிமைத் திட்டம்',
    description_en: 'Monthly financial assistance of ₹1,000 for eligible women heads of families to improve their livelihood and recognize their uncompensated labor.',
    description_hi: 'योग्य महिला परिवार प्रमुखों को उनकी आजीविका में सुधार करने और उनके अवैतनिक श्रम को मान्यता देने के लिए ₹1,000 की मासिक वित्तीय सहायता।',
    description_ta: 'தகுதியான குடும்பத் தலைவிகளின் வாழ்வாதாரத்தை மேம்படுத்தவும், அவர்கள் ஊதியமில்லாமல் செய்யும் உழைப்பை அங்கீகரிக்கவும் மாதந்தோறும் ₹1,000 நிதியுதவி.',
    category: 'womens_welfare',
    issuing_department: 'Special Programme Implementation Department, Tamil Nadu',
    benefits_en: '₹1,000 monthly direct bank transfer.',
    benefits_hi: '₹1,000 मासिक प्रत्यक्ष बैंक हस्तांतरण।',
    benefits_ta: 'மாதம் ₹1,000 நேரடியாக வங்கிக் கணக்கில் வரவு.',
    official_link: 'https://kmut.tn.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-amma-vodi',
    name_en: 'TN Amma Vodi (Education Support for Mothers)',
    name_hi: 'टीएन अम्मा वोडी (माताओं के लिए शिक्षा सहायता)',
    name_ta: 'அம்மா ஒடி (தாய்மார்களுக்கான கல்வி உதவி)',
    description_en: 'Provides financial support to mothers from Below Poverty Line families to ensure their children continue their school education without dropping out.',
    description_hi: 'गरीबी रेखा से नीचे के परिवारों की माताओं को वित्तीय सहायता प्रदान करता है ताकि यह सुनिश्चित हो सके कि उनके बच्चे स्कूल की पढ़ाई बीच में न छोड़ें।',
    description_ta: 'வறுமைக் கோட்டிற்கு கீழ் உள்ள குடும்பங்களைச் சேர்ந்த தாய்மார்கள் தங்கள் குழந்தைகளை பள்ளியில் தொடர்ந்து படிக்க வைப்பதை உறுதிசெய்ய நிதியுதவி வழங்குகிறது.',
    category: 'education',
    issuing_department: 'Department of School Education, Tamil Nadu',
    benefits_en: 'Annual financial incentive to the mother/guardian.',
    benefits_hi: 'माता/अभिभावक को वार्षिक वित्तीय प्रोत्साहन।',
    benefits_ta: 'தாய்/பாதுகாவலருக்கு ஆண்டு நிதி ஊக்கத்தொகை.',
    official_link: 'https://cms.tn.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-thozhilalar-urimai-thittam',
    name_en: 'Thozhilalar Urimai Thittam (Unemployment Allowance)',
    name_hi: 'तोज़िलालर उरिमई थित्तम (बेरोजगारी भत्ता)',
    name_ta: 'தொழிலாளர் உரிமைத் திட்டம் (வேலையின்மை உதவித்தொகை)',
    description_en: 'Unemployment allowance provided to registered graduates and post-graduates in the Employment Exchange waiting for suitable jobs.',
    description_hi: 'रोजगार कार्यालय में पंजीकृत और उपयुक्त नौकरी की प्रतीक्षा कर रहे स्नातकों और स्नातकोत्तरों को बेरोजगारी भत्ता प्रदान किया जाता है।',
    description_ta: 'வேலைவாய்ப்பு அலுவலகத்தில் பதிவு செய்து தகுதியான வேலைக்காகக் காத்திருக்கும் பட்டதாரிகள் மற்றும் முதுநிலைப் பட்டதாரிகளுக்கு வேலைவாய்ப்பற்றோர் உதவித்தொகை வழங்கப்படுகிறது.',
    category: 'welfare',
    issuing_department: 'Department of Employment and Training, Tamil Nadu',
    benefits_en: 'Monthly financial assistance up to 3 years based on qualification.',
    benefits_hi: 'योग्यता के आधार पर 3 वर्ष तक मासिक वित्तीय सहायता।',
    benefits_ta: 'கல்வித் தகுதியின் அடிப்படையில் 3 ஆண்டுகள் வரை மாத நிதியுதவி.',
    official_link: 'https://tnvelaivaaippu.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-new-entrepreneur-cum-enterprise',
    name_en: 'New Entrepreneur-cum-Enterprise Development Scheme (NEEDS)',
    name_hi: 'नई उद्यमी-सह-उद्यम विकास योजना (NEEDS)',
    name_ta: 'புதிய தொழில்முனைவோர் மற்றும் தொழில் மேம்பாட்டுத் திட்டம் (NEEDS)',
    description_en: 'Assists educated youth, particularly from SC/ST and other marginalized communities, to become first-generation entrepreneurs with capital subsidy and interest subvention.',
    description_hi: 'शिक्षित युवाओं, विशेषकर अनुसूचित जाति/अनुसूचित जनजाति और अन्य हाशिए के समुदायों से, पूंजीगत सब्सिडी और ब्याज छूट के साथ पहली पीढ़ी के उद्यमी बनने में सहायता करता है।',
    description_ta: 'படித்த இளைஞர்கள், குறிப்பாக எஸ்சி/எஸ்டி மற்றும் இதர நலிந்த பிரிவினரை, மூலதன மானியம் மற்றும் வட்டி மானியத்துடன் முதல் தலைமுறை தொழில்முனைவோராக ஆக உதவுகிறது.',
    category: 'startup_funding',
    issuing_department: 'MSME Department, Tamil Nadu',
    benefits_en: '25% Capital Subsidy up to ₹75 lakh and 3% Interest Subvention.',
    benefits_hi: '₹75 लाख तक की 25% पूंजीगत सब्सिडी और 3% ब्याज छूट।',
    benefits_ta: '₹75 லட்சம் வரை 25% மூலதன மானியம் மற்றும் 3% வட்டி மானியம்.',
    official_link: 'https://msmeonline.tn.gov.in/needs/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-vazhndhu-kattuvom',
    name_en: 'Vazhndhu Kattuvom Project',
    name_hi: 'वाझंधू कट्टुवोम परियोजना',
    name_ta: 'வாழ்ந்து காட்டுவோம் திட்டம்',
    description_en: 'A rural transformation project focusing on livelihoods, enterprises, and income generation for the rural poor and marginalized groups.',
    description_hi: 'ग्रामीण गरीबों और हाशिए के समूहों के लिए आजीविका, उद्यम और आय सृजन पर केंद्रित एक ग्रामीण परिवर्तन परियोजना।',
    description_ta: 'ஊரக ஏழைகள் மற்றும் நலிந்த பிரிவினருக்கான வாழ்வாதாரங்கள், தொழில்கள் மற்றும் வருவாய் ஈட்டுதல் ஆகியவற்றை மையமாகக் கொண்ட ஒரு ஊரக மாற்றத் திட்டம்.',
    category: 'welfare',
    issuing_department: 'Rural Development and Panchayat Raj Department, Tamil Nadu',
    benefits_en: 'Skill training, enterprise matching grants, and livelihood support.',
    benefits_hi: 'कौशल प्रशिक्षण, उद्यम मिलान अनुदान और आजीविका सहायता।',
    benefits_ta: 'திறன் பயிற்சி, தொழில் தொடங்க மானியம் மற்றும் வாழ்வாதார ஆதரவு.',
    official_link: 'https://www.vazhndhukattuvom.tn.gov.in/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  },
  {
    id: 'tn-chief-minister-comprehensive-health',
    name_en: 'Chief Minister’s Comprehensive Health Insurance Scheme (CMCHIS)',
    name_hi: 'मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना (CMCHIS)',
    name_ta: 'முதலமைச்சரின் விரிவான மருத்துவக் காப்பீட்டுத் திட்டம் (CMCHIS)',
    description_en: 'Provides cashless treatment up to ₹5 lakh per family per year for life-threatening diseases at empaneled government and private hospitals.',
    description_hi: 'पैनल में शामिल सरकारी और निजी अस्पतालों में जीवन-घातक बीमारियों के लिए प्रति परिवार प्रति वर्ष ₹5 लाख तक का मुफ्त इलाज प्रदान करता है।',
    description_ta: 'அங்கீகரிக்கப்பட்ட அரசு மற்றும் தனியார் மருத்துவமனைகளில் உயிருக்கு ஆபத்தான நோய்களுக்கு ஒரு குடும்பத்திற்கு ஆண்டுக்கு ₹5 லட்சம் வரை கட்டணமில்லா சிகிச்சை வழங்குகிறது.',
    category: 'healthcare',
    issuing_department: 'Health and Family Welfare Department, Tamil Nadu',
    benefits_en: 'Health insurance cover of ₹5,00,000 per family per year.',
    benefits_hi: 'प्रति परिवार प्रति वर्ष ₹5,00,000 का स्वास्थ्य बीमा कवर।',
    benefits_ta: 'ஒரு குடும்பத்திற்கு ஆண்டுக்கு ₹5,00,000 மருத்துவக் காப்பீடு.',
    official_link: 'https://www.cmchistn.com/',
    deadline: null,
    state: 'Tamil Nadu',
    last_verified_at: '2026-07-25',
    required_documents: []
  }
];

export const TAMILNADU_ELIGIBILITY_RULES = [
  {
    id: 'rule-tn-breakfast-edu',
    scheme_id: 'tn-chief-minister-breakfast',
    field: 'education_level',
    operator: 'in',
    value: ['Primary School (Class 1-5)'],
    match_reason_en: 'Primary school students in government schools are eligible for free breakfast.',
    match_reason_hi: 'सरकारी स्कूलों में प्राथमिक विद्यालय के छात्र मुफ्त नाश्ते के लिए पात्र हैं।',
    match_reason_ta: 'அரசுப் பள்ளிகளில் படிக்கும் தொடக்கப் பள்ளி மாணவர்கள் இலவச காலை உணவு பெற தகுதியுடையவர்கள்.'
  },
  {
    id: 'rule-tn-pudhumai-penn',
    scheme_id: 'tn-moovalur-ramamirtham-scholarship',
    field: 'gender',
    operator: 'equals',
    value: 'female',
    match_reason_en: 'Scheme is specifically for girl students pursuing higher education.',
    match_reason_hi: 'यह योजना विशेष रूप से उच्च शिक्षा प्राप्त करने वाली छात्राओं के लिए है।',
    match_reason_ta: 'இத்திட்டம் உயர்கல்வி பயிலும் மாணவிகளுக்காக பிரத்தியேகமாகச் செயல்படுத்தப்படுகிறது.'
  },
  {
    id: 'rule-tn-magalir-urimai',
    scheme_id: 'tn-kalaignar-magalir-urimai-thittam',
    field: 'gender',
    operator: 'equals',
    value: 'female',
    match_reason_en: 'Eligible women heads of families qualify for monthly assistance.',
    match_reason_hi: 'योग्य महिला परिवार प्रमुख मासिक सहायता के लिए पात्र हैं।',
    match_reason_ta: 'தகுதியான குடும்பத் தலைவிகள் மாத நிதியுதவி பெற தகுதியுடையவர்கள்.'
  },
  {
    id: 'rule-tn-cmchis-income',
    scheme_id: 'tn-chief-minister-comprehensive-health',
    field: 'annual_income_band',
    operator: 'in',
    value: ['below_1L', '1L_2L'],
    match_reason_en: 'Families with annual income below ₹1.2 lakhs are eligible for CMCHIS.',
    match_reason_hi: '₹1.2 लाख से कम वार्षिक आय वाले परिवार CMCHIS के लिए पात्र हैं।',
    match_reason_ta: 'ஆண்டு வருமானம் ₹1.2 லட்சத்திற்கும் குறைவாக உள்ள குடும்பங்கள் CMCHIS திட்டத்திற்குத் தகுதியானவர்கள்.'
  }
];

export const TAMILNADU_RAG_DOCUMENTS = [
  {
    id: 'doc-tn-pudhumaipenn-clause-1',
    scheme_id: 'tn-moovalur-ramamirtham-scholarship',
    clause_label: 'Pudhumai Penn Scheme — Eligibility & Monthly ₹1,000 Stipend Rules',
    content: 'Girls who have studied from Class 6 to Class 12 entirely in Tamil Nadu government or government-aided schools are eligible for ₹1,000 per month stipend when pursuing higher education. The benefit continues until the completion of the enrolled course. Applications are processed through the scheme portal with Aadhaar and bank account verification.',
    language: 'en',
    last_verified_at: '2026-07-25'
  },
  {
    id: 'doc-tn-magalir-urimai-clause-1',
    scheme_id: 'tn-kalaignar-magalir-urimai-thittam',
    clause_label: 'Magalir Urimai Thittam — Eligibility Criteria & Exclusions',
    content: 'Kalaignar Magalir Urimai Thittam provides ₹1,000 per month to eligible women who are family heads. Women whose family annual income does not exceed ₹2,50,000 and who are not income tax payees are eligible. Government employees, pensioners receiving monthly pension above ₹1,500, and those owning four-wheelers are excluded from the scheme.',
    language: 'en',
    last_verified_at: '2026-07-25'
  },
  {
    id: 'doc-tn-breakfast-clause-1',
    scheme_id: 'tn-chief-minister-breakfast',
    clause_label: 'CM Breakfast Scheme — Coverage & Nutritional Standards',
    content: 'The Chief Minister Breakfast Scheme covers students of Classes 1 to 5 in all government elementary schools across Tamil Nadu. The breakfast menu includes semiya upma, pongal, or other nutritious items meeting ICDS standards. No application is required; students enrolled in government schools are automatically covered.',
    language: 'en',
    last_verified_at: '2026-07-25'
  }
];
